In [18]:
#Assignment 5: Arrays and Text Clustering
#Task 1: Data normalization using array operations and broadcasting

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import pandas as pd
from nltk.cluster import KMeansClusterer, cosine_distance


def minmax_norm(array):
    
    min_arr = [];
    max_min_arr = [];
    nomalized_arr = [];
    min_arr = np.amin(array, axis=1)
    max_arr = np.amax(array, axis=1)
    max_min_arr = max_arr-min_arr;

    print array
    print min_arr
    print max_min_arr
    nomalized_arr = ((0.0+array.T-min_arr)/max_min_arr).T
    
    print "------ task 1 ------"
    print "input:"
    print array
    print "shape of the input:"
    print array.shape
    print "shape of the output:"
    print nomalized_arr.shape
    print "ouput:"
    print nomalized_arr
    print "------ end of task 1 ------\n"
    
# MAIN BLOCK
if __name__ == "__main__": 
    array = np.random.randint(0,10,(4,3))
    minmax_norm(array);

#Task 2: Text Clustering
if __name__ == "__main__":
    import pickle
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.cluster import KMeans
    from sklearn import metrics

    print "------ task 2 ------"
    data=pickle.load(open("4NewsGroup.pkl","r"))

    text,target=zip(*data)
    text=list(text)
    target=list(target)

    tfidf_vect = TfidfVectorizer(stop_words="english", min_df=10, max_df=0.9) 
    dtm= tfidf_vect.fit_transform(text)

    num_clusters = 4

    clusterer = KMeansClusterer(num_clusters, cosine_distance, repeats=5)
    clusters = clusterer.cluster(dtm.toarray(), assign_clusters=True)

    order_centroids = np.array(clusterer.means()).argsort()[:, ::-1] 
    voc=tfidf_vect.vocabulary_
    voc_lookup={tfidf_vect.vocabulary_[word]:word \
                for word in tfidf_vect.vocabulary_}

    for i in range(num_clusters):
        top_words=[voc_lookup[word_index] \
                   for word_index in order_centroids[i, :20]]
        print("Cluster %d: %s " % (i, "; ".join(top_words)))


    cluster_dict={0:0, 1:2, 2:1, 3:3}
    predicted_clusters=[cluster_dict[i] for i in clusters]
 
    #print target
    print(metrics.classification_report(target, predicted_clusters))
    
    # get confusion matrix
    df=pd.DataFrame(zip(target, predicted_clusters), columns=['actual','predict'])
    df.groupby(['predict','actual']).size()
    print df

    # according to confusion matrix, we can get cluster_dict as follows:
    # {0:0, 1:2, 2:1, 3:3}
    # also we can get this conclusion by scanning and labeling(adding meaningful labels) the sample in the excel first, 
    # then mapping with the name of the clusters if they looks similar.
    
    ## Write down the name of each cluster as comments in your code.
    # cluster 0: edu.math (label 0 in excel)
    # cluster 1: edu.sport (label 2 in excel)
    # cluster 2: edu.engineering (label 1 in excel)
    # cluster 3: edu.astronomy.geography (label 3 in excel)

    print "name of each cluster base on the weight of TfIdf:"
    print "cluster 0: edu.math (label 0 in excel)\ncluster 1: edu.sport (label 2 in excel)\ncluster 2: edu.engineering (label 1 in excel)\ncluster 3: edu.astronomy.geography (label 3 in excel)\n"
    print "------ end of task 2 ------"

[[7 7 9]
 [3 9 8]
 [8 3 2]
 [1 1 7]]
[7 3 2 1]
[2 6 6 6]
------ task 1 ------
input:
[[7 7 9]
 [3 9 8]
 [8 3 2]
 [1 1 7]]
shape of the input:
(4, 3)
shape of the output:
(4, 3)
ouput:
[[ 0.          0.          1.        ]
 [ 0.          1.          0.83333333]
 [ 1.          0.16666667  0.        ]
 [ 0.          0.          1.        ]]
------ end of task 1 ------

------ task 2 ------
Cluster 0: edu; mac; apple; drive; se; monitor; problem; thanks; university; quadra; does; scsi; posting; com; know; simms; nntp; use; card; host 
Cluster 1: edu; baseball; year; cs; team; game; article; writes; university; players; com; games; runs; jewish; posting; host; nntp; win; think; season 
Cluster 2: car; com; edu; cars; article; writes; hp; oil; just; engine; don; like; good; posting; usa; nntp; host; university; distribution; new 
Cluster 3: space; nasa; edu; access; henry; gov; alaska; moon; com; digex; pat; toronto; orbit; writes; article; launch; just; earth; like; lunar 
             pre

predict  actual
0        0         539
         1           8
         2           4
         3          12
1        0          15
         1         556
         2          24
         3          27
2        0          21
         1          26
         2         565
         3          45
3        0           3
         1           4
         2           4
         3         509
dtype: int64

      actual  predict
0          1        1
1          1        1
2          1        1
3          0        0
4          0        0
5          1        1
6          3        3
7          2        2
8          0        0
9          3        3
10         1        3
11         1        1
12         0        0
13         3        3
14         0        0
15         0        0
16         0        0
17         2        2
18         2        2
19         2        2
20         3        3
21         0        0
22         2        2
23         2        2
24         0        0
25         0        2
26         3        3
27         3        3
28         3        3
29         3        3
...      ...      ...
2332       2        2
2333       0        0
2334       2        2
2335       3        3
2336       0        0
2337       1        1
2338       1        1
2339       2        2
2340       0        0
2341       3        3
2342       2        2
2343       3        3
2344       0        0
2345      